# Generated by Django 3.1.7 on 2021-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210403_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prize',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
