# Generated by Django 3.1.7 on 2021-04-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='prize',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
