# Generated by Django 3.1.7 on 2021-04-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210420_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(default='50%', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='units_sold',
            field=models.IntegerField(default=0),
        ),
    ]
